#!/usr/bin/env node
'use strict';

// Demo data so the site shows something real to look at: a couple of labs, a
// few products, and batches that each carry a lab report PDF — including one
// filed under no product and one left as a draft. Idempotent: it clears the
// demo rows it owns first, so running it twice does not pile up duplicates.
//
//   npm run seed:demo
//
// The PDFs are generated here, one plain page each and marked as demonstration
// documents, standing in for the laboratory's real report.

const fsp = require('fs/promises');
const db = require('../src/config/db');
const storage = require('../src/lib/storage');
const { batchKey } = require('../src/lib/validate');

/**
 * A minimal one-page PDF of text lines, built by hand so the seed needs no PDF
 * library. ASCII text only: it uses the standard Helvetica font, unembedded.
 */
function demoPdf(lines) {
  const esc = (s) => String(s).replace(/[\\()]/g, (c) => `\\${c}`);
  let y = 730;
  const content = lines.map(([size, text]) => {
    const op = `BT /F1 ${size} Tf 72 ${y} Td (${esc(text)}) Tj ET`;
    y -= size + 14;
    return op;
  }).join('\n');

  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
    `<< /Length ${Buffer.byteLength(content, 'latin1')} >>\nstream\n${content}\nendstream`,
  ];

  let pdf = '%PDF-1.4\n';
  const offsets = [];
  objects.forEach((body, i) => {
    offsets.push(Buffer.byteLength(pdf, 'latin1'));
    pdf += `${i + 1} 0 obj\n${body}\nendobj\n`;
  });
  const xref = Buffer.byteLength(pdf, 'latin1');
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  pdf += offsets.map((at) => `${String(at).padStart(10, '0')} 00000 n \n`).join('');
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;
  return Buffer.from(pdf, 'latin1');
}

async function main() {
  console.log('Seeding demo data…');

  // Report files on disk first, while their rows still say where they are.
  for (const f of await db.query('SELECT file_path FROM coa_files')) {
    await storage.remove(f.file_path);
  }

  // Wipe in FK order. The results tables are no longer written, but clearing
  // them keeps a re-seed from leaving rows behind from the older design.
  await db.query('DELETE FROM results');
  await db.query('DELETE FROM result_panels');
  await db.query('DELETE FROM coa_files');
  await db.query('DELETE FROM lookups');
  await db.query('DELETE FROM coa_downloads');
  await db.query('DELETE FROM batches');
  await db.query('DELETE FROM products');
  await db.query('DELETE FROM labs');

  await db.query(
    `INSERT INTO labs (name, slug, license_no, accreditation, website, is_active)
     VALUES (?, ?, ?, ?, ?, 1)`,
    ['Anresco Laboratories', 'anresco', 'C8-0000123-LIC', 'ISO/IEC 17025:2017', 'https://www.anresco.com']
  );
  await db.query(
    `INSERT INTO labs (name, slug, license_no, accreditation, website, is_active)
     VALUES (?, ?, ?, ?, ?, 1)`,
    ['SC Labs', 'sc-labs', 'C8-0000456-LIC', 'ISO/IEC 17025:2017', 'https://www.sclabs.com']
  );

  const products = [
    { name: 'Calm Gummies', category: 'Gummies', size: '20 ct', sku: 'SF-GUM-CALM' },
    { name: 'Full-Spectrum Oil', category: 'Tincture', size: '30 ml', sku: 'SF-OIL-FS30' },
    { name: 'Recovery Balm', category: 'Topical', size: '50 g', sku: 'SF-BALM-REC' },
    { name: 'Sleep Softgels', category: 'Capsules', size: '30 ct', sku: 'SF-CAP-SLEEP' },
  ];
  const productIds = {};
  let order = 0;
  for (const p of products) {
    const slug = p.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
    productIds[p.name] = (await db.query(
      `INSERT INTO products (name, slug, sku, category, size_label, description, sort_order, is_published)
       VALUES (?, ?, ?, ?, ?, ?, ?, 1)`,
      [p.name, slug, p.sku, p.category, p.size,
       `${p.name} — every production run independently tested and published here.`, order++]
    )).insertId;
  }

  const shard = storage.shardDir();
  await storage.ensureDir(shard);

  // A batch and its report, dated `daysAgo`. `pub` false makes a draft.
  async function makeBatch({ code, product = null, pub = true, daysAgo = 0 }) {
    const when = `NOW() - INTERVAL ${Number(daysAgo)} DAY`;
    const id = (await db.query(
      `INSERT INTO batches (product_id, batch_code, batch_key, is_published, created_at)
       VALUES (?, ?, ?, ?, ${when})`,
      [product ? productIds[product] : null, code, batchKey(code), pub ? 1 : 0]
    )).insertId;

    const pdf = demoPdf([
      [22, 'Certificate of Analysis'],
      [11, 'Demonstration document - not a genuine laboratory report'],
      [14, `Product: ${product || 'Kava-Kratom Shot'}`],
      [14, `Lot number: ${code}`],
      [11, 'All panels tested: PASS'],
      [9, 'Generated by scripts/seed-demo.js for the Super Feels COA portal.'],
    ]);
    const stored = storage.storedName(`${code}.pdf`);
    const relPath = `${shard}/${stored}`.replace(/\\/g, '/');
    await fsp.writeFile(storage.resolve(relPath), pdf);
    await db.query(
      `INSERT INTO coa_files (batch_id, original_filename, stored_filename, file_path, mime_type, file_size, is_primary, created_at)
       VALUES (?, ?, ?, ?, 'application/pdf', ?, 1, ${when})`,
      [id, `${code}-coa.pdf`, stored, relPath, pdf.length]
    );
    return id;
  }

  await makeBatch({ code: 'SF-2409-A12', product: 'Calm Gummies', daysAgo: 20 });
  await makeBatch({ code: 'SF-2410-B07', product: 'Full-Spectrum Oil', daysAgo: 12 });
  await makeBatch({ code: 'SF-2408-C03', product: 'Recovery Balm', daysAgo: 30 });
  await makeBatch({ code: 'SF-2411-D19', product: 'Sleep Softgels', daysAgo: 5 });
  // A second Calm Gummies batch, so the report shows siblings.
  await makeBatch({ code: 'SF-2405-A04', product: 'Calm Gummies', daysAgo: 60 });
  // Filed with nothing but a code and the PDF — the PDF names the product.
  await makeBatch({ code: 'SO-2603-K01', daysAgo: 2 });
  // A draft, so the admin "needs attention" list is not empty.
  await makeBatch({ code: 'SF-2412-B11', product: 'Full-Spectrum Oil', pub: false, daysAgo: 1 });

  // A few lookups so the analytics chart is not blank.
  const found = await db.query('SELECT id FROM batches WHERE is_published = 1 LIMIT 3');
  for (let d = 0; d < 14; d++) {
    const when = `DATE_SUB(NOW(), INTERVAL ${d} DAY)`;
    const hits = Math.floor(Math.random() * 6) + 1;
    for (let i = 0; i < hits; i++) {
      const b = found[Math.floor(Math.random() * found.length)];
      await db.query(
        `INSERT INTO lookups (query, batch_id, found, source, created_at) VALUES ('SF-DEMO', ?, 1, 'qr', ${when})`,
        [b.id]
      );
    }
    if (Math.random() > 0.5) {
      await db.query(
        `INSERT INTO lookups (query, batch_id, found, source, created_at) VALUES ('SF-9999-XX', NULL, 0, 'form', ${when})`
      );
    }
  }

  console.log('Done. Try SF-2409-A12, SO-2603-K01 (no product), or SF-2412-B11 (a draft, so not public).');
  await db.pool.end();
}

main().catch(async (err) => {
  console.error(err);
  try { await db.pool.end(); } catch {}
  process.exit(1);
});
